version: '3.9'

x-settings: &global
  environment:
    - HOST="*"
    - SECRET_KEY='django-insecure-j)rc7@f%y3dn1(+v0*@c-*zov6&af(3b315*qj8y^ujt%mv7ux'
    - DEBUG=True
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_DB=postgres
    - PGDATA=/var/lib/postgresql/data
    - DB_NAME=postgres
    - DB_USER=postgres
    - DB_PASSWORD=postgres
    - DB_HOST=database
    - DB_PORT=5432

services:
  api:
    container_name: api
    command: python manage.py runserver 0.0.0.0:8080
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    <<: *global
    depends_on:
      - database

  database:
    image: postgres:13.4
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    <<: *global

volumes:
  postgres_data:
